apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: LoadBalancer
  selector:
    app: springboot        # must match the label on your Deployment’s Pods
  ports:
    - port: 80             # the port that clients (Postman) will hit
      targetPort: 8080     # the port your Spring Boot container listens on
